### ISSUE TITLE
Type check

### ISSUE THREAD

**Issue by johnvtan** [mfekadu/rc#23]

**Comment by mfekadu** [comment]
## Expected Functionality
* Ints are cool
  * `Integer` is the type name
  * `42` is `Integer`
* Bools are cool
  * `Boolean` is the type name
  * `#t` is `Boolean`
    * also is non-zero integer under the hood (e.g. `1`)
  * `#f` is `Boolean`
    * also is `0` integer under the hood
* `not` is a special function
  * `(not #f)` has return type `Boolean`
  * `(not #t)` has return type `Boolean`
  * `(not 0)` has return type `Boolean` and the expected output is `1`
  * `(not 1)` has return type `Boolean` and the expected output is `0`
  * `(not 42)` has return type `Boolean` and the expected output is `0`
* `read`has return type `Integer`
  * TODO: implement `read` with runtime.c and test it...
  * QUESTION: why can't read output a boolean?
    * possible answer: same thing under the hood?
* `(let [[var expr]] body)` expressions
  * return type depends on the `body`
* `(if cmp thn els)` expressions
  * return type depends `thn` and `els` and **_they should have the same return type_**
* `(cmp int_exp int_exp)` expressions
   * return type is `Boolean`
* everything else is `Integer` see image below
  * <img width="721" alt="image" src="https://user-images.githubusercontent.com/11131250/64198381-1ec13a80-ce56-11e9-8e35-9468e33d5e05.png">

**Comment by johnvtan** [comment]
:fire: :fire:
