### ISSUE TITLE
Shrink

### ISSUE THREAD

**Issue by johnvtan** [mfekadu/rc#24]

**Comment by mfekadu** [comment]
## Expected Functionality
* remove operations and replace with other operations to _shrink_ R2
  * subtraction `-`
    * `(- e1 e2)` -> `(+ e1 (- e2))`
      * `(- 2 2)` -> `(+ 2 (- 2))`
      * `(- 1 2)` -> `(+ 1 (- 2))`
  * `and`
    * `(and e1 e2)` -> `(if (eq? e1 #t) (eq? e2 #t) #f)`
    * `(and #t #t)` -> `(if (eq? #t #t) (eq? #t #t) #f)`
    * `(and #t #f)` -> `(if (eq? #t #t) (eq? #f #t) #f)`
    * `(and #f #f)` -> `(if (eq? #f #t) (eq? #f #t) #f)`
  * `or`
    * `(or #t #t)` -> ???
    * `(or #t #f)` -> ???
    * `(or #f #f)` -> ???
  * `<=`
    * `(<= e1 e2)` -> `(not (< e2 e1)`
      * `(<= 2 2)` -> `(not (< 2 2)`
      * `(<= 1 2)` -> `(not (< 2 1)`
  * `>`
    * `(> e1 e2)` -> `(not (??? e2 e1)`
      * `(> 2 2)` -> `(not (??? 2 2)`
      * `(> 1 2)` -> `(not (??? 2 1)`
  * `>=`
    * `(>= e1 e2)` -> `(not (??? e2 e1)`
      * `(>= 2 2)` -> `(not (??? 2 2)`
      * `(>= 1 2)` -> `(not (??? 2 1)`



![](https://user-images.githubusercontent.com/11131250/64198381-1ec13a80-ce56-11e9-8e35-9468e33d5e05.png)


<img width="834" alt="image" src="https://user-images.githubusercontent.com/11131250/64218152-80050000-ce8e-11e9-8e29-9e54cfa4b206.png">

<img width="829" alt="image" src="https://user-images.githubusercontent.com/11131250/64218195-a88cfa00-ce8e-11e9-8cc8-a2acc754ce4e.png">

![image](https://user-images.githubusercontent.com/11131250/64290435-18a18b80-cf34-11e9-846c-0f1c63563008.png)

**Comment by mfekadu** [comment]
```
> cat equivalence.py
#!/usr/bin/env python3
x = 1
ys = [0, 1, 2]

for y in ys:
    g_x_y = x > y
    equiv = False if (x < y) else (not x == y)
    assert g_x_y == equiv, "{} ?? {}".format(x, y)

    ge_x_y = x >= y
    equiv = not (x < y)
    assert ge_x_y == equiv, "{} ?? {}".format(x, y)

    le_x_y = x <= y
    equiv = True if (x < y) else (x == y)
    assert le_x_y == equiv, "{} ?? {}".format(x, y)

    minus_x_y = x - y
    equiv = x + (-y)
    assert minus_x_y == equiv, "{} ?? {}".format(x, y)


ps = (True, False)
qs = (False, True)

for p in ps:
    for q in qs:
        and_p_q = (p and q)
        equiv = (q == True) if (p == True) else False
        assert and_p_q == equiv, "{} ?? {}".format(p, q)

        or_p_q = (p or q)
        equiv = (q == True) if (p == False) else True
        assert or_p_q == equiv, "{} ?? {}".format(p, q)
> ./equivalence.py
>
```
