### ISSUE TITLE
Explicate Control

### ISSUE THREAD

**Issue by johnvtan** [mfekadu/rc#26]

**Comment by mfekadu** [comment]
see #25 because there's some good information on how to design E.C.

**Comment by mfekadu** [comment]
TODO: write more program tests

**Comment by mfekadu** [comment]
Here's the plan:
* ![2019-09-04 22 05 13](https://user-images.githubusercontent.com/11131250/64364677-67f1c580-cfe1-11e9-9003-bcd356f89dc3.png)

**Comment by johnvtan** [comment]
Some things I realized about `rco` and `ec`:

### In the output of `rco`, `if` statement conditions are always very simple
The output of `rco` never produces `if` statements that contain anything other than `#f`, `#t`, or a symbol in the condition of an if statement. This means that we'll never get the following:
```racket
(if (if (not #t) 1 2) 3 4)
```

If you look at this code (from `rco-exp` in `rco.rkt`), you'll see why:
```racket
 52     [`(if ,cnd ,thn ,els)
 53       ; here, we're conservative and always insert a temp for the condition (unless it's just #f or #t)
 54       ; otherwise we (might?) have problems with a case like:
 55       ;     (if (not #t) 1 2)
 56       ; Should (not #t) be considered complex here and be simplified? I'm not sure.
 57 
 58       ; Similarly, if we get a case like:
 59       ;     (if (if (not #t) 1 2) 3 4)
 60       ; Then we should expect to get:
 61       ;     (let ([t1 
 62       ;             (let ([t2 (not #t)]) (if t2 1 2))])) ; lets nested inside lets
 63       ;           3
 64       ;           4)
 65       (define-values [rcod-cnd ret-alist] (rco-arg cnd))
 66       (values `(if ,rcod-cnd ,(rco thn) ,(rco els)) ret-alist)]

```
By calling `rco-arg` on `cnd`, we're basically saying that we always are aiming to simplify the condition of if statements. The output of `rco-arg` will either be an atom (`#t` or `#f`), or a temporary variable name and an alist that maps from that temporary variable name to the `if` statement.

This results in an extra assignment for nearly every `if` statement, but makes it easier for `ec` to be developed.

### Did we mix up `rco` and `ec`?
Kind of interestingly, `rco` is doing like part of `ec`'s job by turning statements like 
```racket
1 (let ([y (let ([x 20]) x)]) (+ y 1))
```
into:
```racket
2 (let ([x 20]) 
    (let ([y x])
       (+ y 1)))
```
which can be pretty directly translated to
```
(seq (assign x 20)
   (seq (assign y x)
     (return (+ y 1))))
```
which is part of `ec`'s job to turn nested code into sequential code. This makes me wonder if we decided that `let` statements in assignment position were not complex and didn't change the the expression in `1` into `2`, would `ec` produce equivalent `C1` code?

This makes me also think that this is why we're having trouble separating the development of `ec` and `rco` because it feels like they're very tightly coupled.
